import {NgTemplateOutlet} from '@angular/common';
import {Component, inject, input} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {
  TuiButton,
  TuiDropdown,
  TuiHint,
  TuiIcon,
  TuiInput,
  TuiLabel,
  TuiNotification,
  TuiTextfield,
} from '@taiga-ui/core';
import {
  TuiChevron,
  TuiDataListWrapper,
  TuiInputChip,
  TuiInputNumber,
  TuiMultiSelect,
  TuiSegmented,
  TuiSelect,
  TuiSwitch,
  TuiTextarea,
} from '@taiga-ui/kit';
import {TuiForm} from '@taiga-ui/layout';
import {
  AUTO_GENERATED_HINT,
  DirectoryItemFormService,
} from '../../core/services/directory-item-form.service';
import {DirectoryStoreService} from '../../core/services/directory-store.service';
import {
  FieldDefinition,
  JSON_FIELD_TYPE_OPTIONS,
  JsonConfigurableFieldType,
  JsonFieldEntry,
} from '../../core/models/directory.models';
import {
  JSON_OBJECT_NESTING_LIMIT_HINT,
  MAX_JSON_OBJECT_NESTING_DEPTH,
} from '../../core/utils/field-definition.util';

@Component({
  selector: 'app-directory-item-fields',
  standalone: true,
  imports: [
    FormsModule,
    NgTemplateOutlet,
    TuiButton,
    TuiChevron,
    TuiDataListWrapper,
    TuiDropdown,
    TuiHint,
    TuiIcon,
    TuiInput,
    TuiInputChip,
    ...TuiInputNumber,
    TuiSegmented,
    TuiLabel,
    TuiNotification,
    TuiSelect,
    TuiSwitch,
    TuiTextarea,
    TuiTextfield,
    TuiForm,
  ],
  templateUrl: './directory-item-fields.component.html',
  styleUrl: './directory-item-fields.component.less',
})
export class DirectoryItemFieldsComponent {
  readonly fields = input.required<FieldDefinition[]>();
  readonly editingItemId = input<string | null>(null);

  readonly form = inject(DirectoryItemFormService);
  private readonly store = inject(DirectoryStoreService);

  readonly autoGeneratedHint = AUTO_GENERATED_HINT;
  readonly objectNestingLimitHint = JSON_OBJECT_NESTING_LIMIT_HINT;
  readonly jsonFieldTypeValues = JSON_FIELD_TYPE_OPTIONS.map((o) => o.value);

  stringifyRef = (id: string): string => {
    for (const dir of this.store.directories()) {
      const item = dir.items.find((i) => i.id === id);
      if (item) {
        const label =
          (item.data['name'] as string) ||
          (item.data['title'] as string) ||
          id;
        return `${label} (${id.slice(0, 8)}…)`;
      }
    }
    return id;
  };

  stringifyIdentity = (value: string): string => value;

  stringifyJsonFieldType = (value: JsonConfigurableFieldType): string =>
    JSON_FIELD_TYPE_OPTIONS.find((o) => o.value === value)?.label || value;

  isJsonObjectTypeDisabled(
    objectLevel: number,
    type: JsonConfigurableFieldType,
  ): boolean {
    return type === 'object' && objectLevel >= MAX_JSON_OBJECT_NESTING_DEPTH;
  }

  disabledJsonFieldTypeHandler = (objectLevel: number) => {
    return (type: JsonConfigurableFieldType): boolean =>
      this.isJsonObjectTypeDisabled(objectLevel, type);
  };

  private readonly disabledJsonFieldTypeHandlerCache = new Map<
    number,
    (type: JsonConfigurableFieldType) => boolean
  >();

  getDisabledJsonFieldTypeHandler(
    objectLevel: number,
  ): (type: JsonConfigurableFieldType) => boolean {
    let handler = this.disabledJsonFieldTypeHandlerCache.get(objectLevel);
    if (!handler) {
      handler = this.disabledJsonFieldTypeHandler(objectLevel);
      this.disabledJsonFieldTypeHandlerCache.set(objectLevel, handler);
    }
    return handler;
  }

  private toNumberOrNull(value: unknown): number | null {
    if (value === '' || value === null || value === undefined) {
      return null;
    }
    const numberValue = Number(value);
    return Number.isNaN(numberValue) ? null : numberValue;
  }

  fieldNumberValue(
    container: Record<string, unknown>,
    field: FieldDefinition,
  ): number | null {
    return this.toNumberOrNull(this.form.fieldValue(container, field));
  }

  setFieldNumberValue(
    container: Record<string, unknown>,
    field: FieldDefinition,
    value: number | null,
  ): void {
    this.form.setFieldValue(container, field, value ?? '');
  }

  jsonNumberValue(entry: JsonFieldEntry): number | null {
    return this.toNumberOrNull(entry.value);
  }

  setJsonNumberValue(entry: JsonFieldEntry, value: number | null): void {
    entry.value = value ?? '';
  }
}
