import {Injectable, inject, signal} from '@angular/core';
import {
  DirectoryItem,
  FieldDefinition,
  FieldType,
  JsonConfigurableFieldType,
  JsonFieldEntry,
} from '../models/directory.models';
import {DirectoryStoreService} from './directory-store.service';
import {ItemFactoryService} from './item-factory.service';
import {MAX_JSON_OBJECT_NESTING_DEPTH} from '../utils/field-definition.util';

export const AUTO_GENERATED_HINT =
  'Значение сгенерируется автоматически после создания объекта';

@Injectable({providedIn: 'root'})
export class DirectoryItemFormService {
  private readonly store = inject(DirectoryStoreService);
  private readonly itemFactory = inject(ItemFactoryService);

  formModel: Record<string, unknown> = {};
  readonly expandedObjectKeys = signal<Record<string, boolean>>({});
  readonly jsonEditModes = signal<Record<string, 'configurator' | 'raw'>>({});
  readonly jsonModeErrors = signal<Record<string, string>>({});

  reset(): void {
    this.formModel = {};
    this.expandedObjectKeys.set({});
    this.jsonEditModes.set({});
    this.jsonModeErrors.set({});
  }

  populate(fields: FieldDefinition[], item?: DirectoryItem): void {
    this.formModel = {};
    this.jsonEditModes.set({});
    this.jsonModeErrors.set({});
    for (const field of fields) {
      const value = item?.data[field.name];
      if (this.isAutoField(field.type)) {
        this.formModel[field.name] = value ?? '';
        continue;
      }
      if (field.isList) {
        if (field.type === 'object') {
          this.formModel[field.name] = this.prepareObjectListValue(field, value);
        } else if (field.type === 'json') {
          this.formModel[field.name] = Array.isArray(value)
            ? value.map((itemValue) => this.objectToJsonEntries(itemValue))
            : [];
        } else {
          this.formModel[field.name] = Array.isArray(value) ? [...value] : [];
        }
      } else if (field.type === 'json') {
        this.formModel[field.name] = this.objectToJsonEntries(
          typeof value === 'string' ? this.safeParseJsonObject(value) : value,
        );
      } else if (field.type === 'object') {
        this.formModel[field.name] = this.prepareObjectValue(field, value);
      } else if (field.type === 'bool') {
        this.formModel[field.name] = Boolean(value);
      } else {
        this.formModel[field.name] = value ?? '';
      }
    }
  }

  buildPayload(
    fields: FieldDefinition[],
    editingId: string | null,
  ): {payload: Record<string, unknown>; error: string | null} {
    const payload: Record<string, unknown> = {};
    for (const field of fields) {
      if (this.isAutoField(field.type) && field.type !== 'uuid') {
        if (editingId) {
          payload[field.name] = this.formModel[field.name];
        }
        continue;
      }

      const normalized = this.normalizeFieldValue(
        field,
        this.formModel[field.name],
        field.name,
      );
      if (normalized.error) {
        return {payload: {}, error: normalized.error};
      }
      const value = normalized.value;
      if (field.validations.some((v) => v.kind === 'required')) {
        const emptyList = field.isList && Array.isArray(value) && !value.length;
        const emptyScalar =
          !field.isList &&
          (value === undefined || value === null || value === '');
        if (emptyList || emptyScalar) {
          return {payload: {}, error: `Поле «${field.name}» обязательно`};
        }
      }
      payload[field.name] = value;
    }

    return {payload, error: null};
  }

  formSnapshot(fields: FieldDefinition[]): string {
    const normalized = fields.map((field) => ({
      name: field.name,
      value: this.formModel[field.name] ?? null,
    }));
    return JSON.stringify(normalized);
  }

  autoFieldValue(field: FieldDefinition, editingItemId: string | null): string {
    if (!editingItemId) {
      return '';
    }
    return this.stringifyValue(this.formModel[field.name]);
  }

  isAutoField(type: FieldType): boolean {
    return type === 'autogenerated_uuid' || type === 'autoincrement';
  }

  referenceOptions(field: FieldDefinition): string[] {
    if (!field.referenceDirectoryId) {
      return [];
    }
    return (
      this.store
        .getDirectory(field.referenceDirectoryId)
        ?.items.map((i) => i.id) || []
    );
  }

  enumOrRefItems(field: FieldDefinition): string[] {
    return field.type === 'enum'
      ? field.enumValues || []
      : this.referenceOptions(field);
  }

  fieldValue(container: Record<string, unknown>, field: FieldDefinition): unknown {
    return container[field.name];
  }

  setFieldValue(
    container: Record<string, unknown>,
    field: FieldDefinition,
    value: unknown,
  ): void {
    container[field.name] = value;
  }

  objectPath(basePath: string, segment: string): string {
    return basePath ? `${basePath}.${segment}` : segment;
  }

  listObjectPath(basePath: string, index: number): string {
    return `${basePath}[${index}]`;
  }

  isObjectExpanded(path: string): boolean {
    const state = this.expandedObjectKeys();
    return state[path] ?? true;
  }

  toggleObjectExpanded(path: string): void {
    this.expandedObjectKeys.update((state) => ({
      ...state,
      [path]: !(state[path] ?? true),
    }));
  }

  objectValue(
    container: Record<string, unknown>,
    field: FieldDefinition,
  ): Record<string, unknown> {
    const current = container[field.name];
    if (current && typeof current === 'object' && !Array.isArray(current)) {
      return current as Record<string, unknown>;
    }
    const next = this.defaultObjectValue(field);
    container[field.name] = next;
    return next;
  }

  objectListValue(
    container: Record<string, unknown>,
    field: FieldDefinition,
  ): Record<string, unknown>[] {
    const current = container[field.name];
    if (Array.isArray(current)) {
      return current.filter(
        (item) => item && typeof item === 'object' && !Array.isArray(item),
      ) as Record<string, unknown>[];
    }
    const next: Record<string, unknown>[] = [];
    container[field.name] = next;
    return next;
  }

  addObjectListItem(container: Record<string, unknown>, field: FieldDefinition): void {
    const list = this.objectListValue(container, field);
    list.push(this.defaultObjectValue(field));
    container[field.name] = [...list];
  }

  removeObjectListItem(
    container: Record<string, unknown>,
    field: FieldDefinition,
    index: number,
  ): void {
    const list = this.objectListValue(container, field).filter((_, i) => i !== index);
    container[field.name] = list;
  }

  jsonEntries(
    container: Record<string, unknown>,
    field: FieldDefinition,
  ): JsonFieldEntry[] {
    const current = container[field.name];
    if (this.isJsonEntryArray(current)) {
      return current;
    }
    const next = this.objectToJsonEntries(
      typeof current === 'string' ? this.safeParseJsonObject(current) : current,
    );
    container[field.name] = next;
    return next;
  }

  jsonListValue(
    container: Record<string, unknown>,
    field: FieldDefinition,
  ): unknown[] {
    const current = container[field.name];
    if (Array.isArray(current)) {
      return current;
    }
    const next: unknown[] = [];
    container[field.name] = next;
    return next;
  }

  jsonListItemEntries(
    container: Record<string, unknown>,
    field: FieldDefinition,
    index: number,
  ): JsonFieldEntry[] {
    const list = [...this.jsonListValue(container, field)];
    const item = list[index];
    if (this.isJsonEntryArray(item)) {
      return item;
    }
    const next = this.objectToJsonEntries(
      typeof item === 'string' ? this.safeParseJsonObject(item) : item,
    );
    list[index] = next;
    container[field.name] = list;
    return next;
  }

  jsonListItemRawText(
    container: Record<string, unknown>,
    field: FieldDefinition,
    index: number,
  ): string {
    const item = this.jsonListValue(container, field)[index];
    if (typeof item === 'string') {
      return item;
    }
    const obj = this.isJsonEntryArray(item)
      ? this.jsonEntriesToObject(item)
      : this.coerceJsonObject(item);
    return JSON.stringify(obj, null, 2);
  }

  setJsonListItemRawText(
    container: Record<string, unknown>,
    field: FieldDefinition,
    index: number,
    path: string,
    text: string,
  ): void {
    const list = [...this.jsonListValue(container, field)];
    list[index] = text;
    container[field.name] = list;
    this.clearJsonModeError(path);
  }

  addJsonListItem(container: Record<string, unknown>, field: FieldDefinition): void {
    const list = this.jsonListValue(container, field);
    container[field.name] = [...list, []];
  }

  removeJsonListItem(
    container: Record<string, unknown>,
    field: FieldDefinition,
    index: number,
  ): void {
    container[field.name] = this.jsonListValue(container, field).filter(
      (_, i) => i !== index,
    );
  }

  isJsonRawMode(path: string): boolean {
    return (this.jsonEditModes()[path] ?? 'configurator') === 'raw';
  }

  jsonModeError(path: string): string {
    return this.jsonModeErrors()[path] ?? '';
  }

  setFieldJsonRawMode(
    container: Record<string, unknown>,
    field: FieldDefinition,
    path: string,
    raw: boolean,
  ): void {
    this.applyJsonRawMode(
      path,
      raw,
      () => container[field.name],
      (value) => {
        container[field.name] = value;
      },
    );
  }

  setJsonFieldRawText(
    container: Record<string, unknown>,
    field: FieldDefinition,
    path: string,
    text: string,
  ): void {
    container[field.name] = text;
    this.clearJsonModeError(path);
  }

  setJsonListItemRawMode(
    container: Record<string, unknown>,
    field: FieldDefinition,
    index: number,
    path: string,
    raw: boolean,
  ): void {
    this.applyJsonRawMode(
      path,
      raw,
      () => this.jsonListValue(container, field)[index],
      (value) => {
        const list = [...this.jsonListValue(container, field)];
        list[index] = value;
        container[field.name] = list;
      },
    );
  }

  addJsonEntry(entries: JsonFieldEntry[]): void {
    entries.push(this.createJsonEntry());
  }

  removeJsonEntry(entries: JsonFieldEntry[], index: number): void {
    entries.splice(index, 1);
  }

  nestedJsonEntries(entry: JsonFieldEntry): JsonFieldEntry[] {
    if (entry.isList) {
      return [];
    }
    if (this.isJsonEntryArray(entry.value)) {
      return entry.value;
    }
    const next = this.objectToJsonEntries(entry.value);
    entry.value = next;
    return next;
  }

  onJsonEntryTypeChange(
    entry: JsonFieldEntry,
    type: JsonConfigurableFieldType,
    objectLevel = 0,
  ): void {
    if (type === 'object' && objectLevel >= MAX_JSON_OBJECT_NESTING_DEPTH) {
      return;
    }
    entry.type = type;
    entry.isList = false;
    entry.value = this.defaultJsonValueForType(type);
  }

  setJsonEntryListMode(entry: JsonFieldEntry, isList: boolean): void {
    if (!!entry.isList === isList) {
      return;
    }

    entry.isList = isList;

    if (isList) {
      if (entry.type === 'object') {
        const current = this.isJsonEntryArray(entry.value)
          ? entry.value
          : this.objectToJsonEntries(entry.value);
        entry.value = [current];
        return;
      }

      const scalar = this.jsonEntrySingleScalar(entry);
      if (entry.type === 'int') {
        entry.value =
          scalar === undefined || scalar === '' ? [] : [String(scalar)];
        return;
      }

      entry.value =
        scalar === undefined || scalar === '' ? [] : [scalar];
      return;
    }

    if (entry.type === 'object') {
      const items = this.jsonObjectListItems(entry);
      entry.value = items[0] ?? [];
      return;
    }

    const list = this.jsonEntryScalarList(entry);
    entry.value = list[0] ?? this.defaultJsonValueForType(entry.type);
  }

  jsonEntryScalarList(entry: JsonFieldEntry): unknown[] {
    if (!entry.isList || !Array.isArray(entry.value)) {
      return [];
    }
    if (
      entry.type === 'object' ||
      this.isJsonEntryArray(entry.value) ||
      this.isJsonObjectListValue(entry.value)
    ) {
      return [];
    }
    return entry.value;
  }

  jsonEntryStringList(entry: JsonFieldEntry): string[] {
    const list = this.jsonEntryScalarList(entry);
    if (!list.length) {
      return list as string[];
    }
    if (list.every((value) => typeof value === 'string')) {
      return list as string[];
    }
    return list.map((value) => String(value ?? ''));
  }

  setJsonEntryStringList(entry: JsonFieldEntry, values: string[]): void {
    if (entry.type === 'int') {
      entry.value = values.map((value) => value.trim());
      return;
    }
    entry.value = values;
  }

  jsonObjectListItems(entry: JsonFieldEntry): JsonFieldEntry[][] {
    if (entry.type !== 'object' || !entry.isList) {
      return [];
    }

    const value = entry.value;
    if (this.isJsonObjectListValue(value)) {
      return value;
    }
    if (this.isJsonEntryArray(value)) {
      return [value];
    }
    return [];
  }

  addJsonObjectListItem(entry: JsonFieldEntry): void {
    const items = this.jsonObjectListItems(entry);
    items.push([]);
    entry.value = items;
    entry.isList = true;
  }

  removeJsonObjectListItem(entry: JsonFieldEntry, index: number): void {
    const items = this.jsonObjectListItems(entry);
    items.splice(index, 1);
    entry.value = items;
  }

  addJsonScalarListItem(entry: JsonFieldEntry): void {
    if (!Array.isArray(entry.value)) {
      entry.value = [];
    }
    (entry.value as unknown[]).push(this.defaultJsonValueForType(entry.type));
    entry.isList = true;
  }

  removeJsonScalarListItem(entry: JsonFieldEntry, index: number): void {
    if (!Array.isArray(entry.value)) {
      return;
    }
    (entry.value as unknown[]).splice(index, 1);
  }

  setJsonScalarListItem(
    entry: JsonFieldEntry,
    index: number,
    value: unknown,
  ): void {
    if (!Array.isArray(entry.value)) {
      entry.value = [];
    }
    (entry.value as unknown[])[index] = value;
  }

  private stringifyValue(value: unknown): string {
    if (value === null || value === undefined) {
      return '';
    }
    if (typeof value === 'object') {
      return JSON.stringify(value);
    }
    return String(value);
  }

  private applyJsonRawMode(
    path: string,
    raw: boolean,
    getValue: () => unknown,
    setValue: (value: unknown) => void,
  ): void {
    const currentMode = this.jsonEditModes()[path] ?? 'configurator';
    const nextMode = raw ? 'raw' : 'configurator';
    if (currentMode === nextMode) {
      return;
    }

    if (raw) {
      const current = getValue();
      const obj = this.isJsonEntryArray(current)
        ? this.jsonEntriesToObject(current)
        : this.coerceJsonObject(current);
      setValue(JSON.stringify(obj, null, 2));
      this.clearJsonModeError(path);
      this.jsonEditModes.update((modes) => ({...modes, [path]: 'raw'}));
      return;
    }

    const current = getValue();
    if (typeof current === 'string') {
      const parsed = this.tryParseJsonObject(current);
      if (parsed.error) {
        this.jsonModeErrors.update((errors) => ({
          ...errors,
          [path]: parsed.error!,
        }));
        return;
      }
      setValue(this.objectToJsonEntries(parsed.value ?? {}));
    } else {
      setValue(this.objectToJsonEntries(this.coerceJsonObject(current)));
    }

    this.clearJsonModeError(path);
    this.jsonEditModes.update((modes) => ({...modes, [path]: 'configurator'}));
  }

  private clearJsonModeError(path: string): void {
    this.jsonModeErrors.update((errors) => {
      if (!errors[path]) {
        return errors;
      }
      const next = {...errors};
      delete next[path];
      return next;
    });
  }

  private coerceJsonObject(value: unknown): Record<string, unknown> {
    if (typeof value === 'string') {
      return this.safeParseJsonObject(value);
    }
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      return value as Record<string, unknown>;
    }
    return {};
  }

  private tryParseJsonObject(
    raw: string,
  ): {value?: Record<string, unknown>; error?: string} {
    try {
      const parsed = JSON.parse(raw || '{}');
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
        return {value: parsed as Record<string, unknown>};
      }
      return {error: 'JSON должен быть объектом {...}'};
    } catch {
      return {error: 'Невалидный JSON'};
    }
  }

  private prepareObjectValue(
    field: FieldDefinition,
    value: unknown,
  ): Record<string, unknown> {
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      return this.hydrateObjectBySchema(field, value as Record<string, unknown>);
    }
    return this.defaultObjectValue(field);
  }

  private prepareObjectListValue(
    field: FieldDefinition,
    value: unknown,
  ): Record<string, unknown>[] {
    if (!Array.isArray(value)) {
      return [];
    }
    return value
      .filter((item) => item && typeof item === 'object' && !Array.isArray(item))
      .map((item) => this.hydrateObjectBySchema(field, item as Record<string, unknown>));
  }

  private defaultObjectValue(field: FieldDefinition): Record<string, unknown> {
    const result: Record<string, unknown> = {};
    for (const child of field.fields ?? []) {
      result[child.name] = this.defaultValueForField(child);
    }
    return result;
  }

  private hydrateObjectBySchema(
    field: FieldDefinition,
    source: Record<string, unknown>,
  ): Record<string, unknown> {
    const result: Record<string, unknown> = {};
    for (const child of field.fields ?? []) {
      const value = source[child.name];
      if (child.type === 'object' && child.isList) {
        result[child.name] = this.prepareObjectListValue(child, value);
      } else if (child.type === 'object') {
        result[child.name] = this.prepareObjectValue(child, value);
      } else if (child.type === 'json' && child.isList) {
        result[child.name] = Array.isArray(value)
          ? value.map((itemValue) => this.objectToJsonEntries(itemValue))
          : [];
      } else if (child.type === 'json') {
        result[child.name] = this.objectToJsonEntries(
          typeof value === 'string' ? this.safeParseJsonObject(value) : value,
        );
      } else if (child.isList) {
        result[child.name] = Array.isArray(value) ? [...value] : [];
      } else if (child.type === 'bool') {
        result[child.name] = Boolean(value);
      } else {
        result[child.name] = value ?? this.defaultValueForField(child);
      }
    }
    return result;
  }

  private defaultValueForField(field: FieldDefinition): unknown {
    if (field.type === 'object') {
      return field.isList ? [] : this.defaultObjectValue(field);
    }
    if (field.type === 'json') {
      return [];
    }
    if (field.isList) {
      return [];
    }
    if (field.type === 'bool') {
      return false;
    }
    return '';
  }

  private normalizeFieldValue(
    field: FieldDefinition,
    rawValue: unknown,
    path: string,
  ): {value: unknown; error?: string} {
    if (field.isList) {
      const list = Array.isArray(rawValue) ? rawValue : [];
      const values: unknown[] = [];
      for (let i = 0; i < list.length; i++) {
        const itemResult = this.normalizeSingleFieldValue(
          {...field, isList: false},
          list[i],
          `${path}[${i}]`,
        );
        if (itemResult.error) {
          return itemResult;
        }
        values.push(itemResult.value);
      }
      return {value: values};
    }
    return this.normalizeSingleFieldValue(field, rawValue, path);
  }

  private normalizeSingleFieldValue(
    field: FieldDefinition,
    rawValue: unknown,
    path: string,
  ): {value: unknown; error?: string} {
    if (field.type === 'int') {
      if (rawValue === '' || rawValue === null || rawValue === undefined) {
        return {value: undefined};
      }
      const numberValue = Number(rawValue);
      if (Number.isNaN(numberValue)) {
        return {value: undefined, error: `Поле «${path}»: ожидается число`};
      }
      return {value: numberValue};
    }

    if (field.type === 'json') {
      return this.normalizeJsonEntries(rawValue, path);
    }

    if (field.type === 'object') {
      if (!rawValue || typeof rawValue !== 'object' || Array.isArray(rawValue)) {
        return {value: this.defaultObjectValue(field)};
      }
      const source = rawValue as Record<string, unknown>;
      const result: Record<string, unknown> = {};
      for (const child of field.fields ?? []) {
        const childResult = this.normalizeFieldValue(
          child,
          source[child.name],
          `${path}.${child.name}`,
        );
        if (childResult.error) {
          return childResult;
        }
        const childValue = childResult.value;
        if (child.validations.some((v) => v.kind === 'required')) {
          const emptyList = child.isList && Array.isArray(childValue) && !childValue.length;
          const emptyScalar =
            !child.isList &&
            (childValue === undefined || childValue === null || childValue === '');
          if (emptyList || emptyScalar) {
            return {value: undefined, error: `Поле «${path}.${child.name}» обязательно`};
          }
        }
        result[child.name] = childValue;
      }
      return {value: result};
    }

    if (field.type === 'bool') {
      return {value: Boolean(rawValue)};
    }

    return {value: rawValue};
  }

  private normalizeJsonEntries(
    rawValue: unknown,
    path: string,
  ): {value: Record<string, unknown>; error?: string} {
    if (typeof rawValue === 'string') {
      const parsed = this.tryParseJsonObject(rawValue);
      if (parsed.error) {
        return {value: {}, error: `Поле «${path}»: ${parsed.error}`};
      }
      return {value: parsed.value ?? {}};
    }

    if (!Array.isArray(rawValue)) {
      if (rawValue && typeof rawValue === 'object' && !Array.isArray(rawValue)) {
        return {value: rawValue as Record<string, unknown>};
      }
      return {value: {}};
    }

    if (!this.isJsonEntryArray(rawValue)) {
      return {value: {}};
    }

    const entries = rawValue;
    const names = new Set<string>();

    for (const entry of entries) {
      const name = entry.name?.trim() ?? '';
      if (!name) {
        return {
          value: {},
          error: `Поле «${path}»: укажите название для всех ключей`,
        };
      }
      if (names.has(name)) {
        return {
          value: {},
          error: `Поле «${path}»: дублируется ключ «${name}»`,
        };
      }
      names.add(name);

      if (entry.type === 'int' && !entry.isList) {
        if (entry.value === '' || entry.value === null || entry.value === undefined) {
          continue;
        }
        if (Number.isNaN(Number(entry.value))) {
          return {
            value: {},
            error: `Поле «${path}.${name}»: ожидается число`,
          };
        }
      }

      if (entry.type === 'object') {
        if (entry.isList) {
          for (let i = 0; i < this.jsonObjectListItems(entry).length; i++) {
            const nested = this.normalizeJsonEntries(
              this.jsonObjectListItems(entry)[i],
              `${path}.${name}[${i}]`,
            );
            if (nested.error) {
              return nested;
            }
          }
        } else {
          const nested = this.normalizeJsonEntries(
            entry.value,
            `${path}.${name}`,
          );
          if (nested.error) {
            return nested;
          }
        }
      }

      if (entry.isList && entry.type === 'int') {
        for (const item of this.jsonEntryScalarList(entry)) {
          if (item === '' || item === null || item === undefined) {
            continue;
          }
          if (Number.isNaN(Number(item))) {
            return {
              value: {},
              error: `Поле «${path}.${name}»: ожидается число`,
            };
          }
        }
      }
    }

    return {value: this.jsonEntriesToObject(entries)};
  }

  private objectToJsonEntries(source: unknown): JsonFieldEntry[] {
    if (!source || typeof source !== 'object' || Array.isArray(source)) {
      return [];
    }

    return Object.entries(source as Record<string, unknown>).map(([name, value]) =>
      this.valueToJsonEntry(name, value),
    );
  }

  private valueToJsonEntry(name: string, value: unknown): JsonFieldEntry {
    const id = this.newJsonEntryId();

    if (Array.isArray(value)) {
      if (!value.length) {
        return {id, name, type: 'string', isList: true, value: []};
      }

      const first = value[0];
      if (typeof first === 'boolean') {
        return {id, name, type: 'bool', isList: true, value: [...value]};
      }
      if (typeof first === 'number' && Number.isFinite(first)) {
        return {
          id,
          name,
          type: 'int',
          isList: true,
          value: value.map((item) => String(item)),
        };
      }
      if (
        first &&
        typeof first === 'object' &&
        !Array.isArray(first) &&
        !this.isJsonEntryArray(first)
      ) {
        return {
          id,
          name,
          type: 'object',
          isList: true,
          value: value.map((item) => this.objectToJsonEntries(item)),
        };
      }
      if (typeof first === 'string') {
        const allUuid = value.every(
          (item) => typeof item === 'string' && this.looksLikeUuid(item),
        );
        return {
          id,
          name,
          type: allUuid ? 'uuid' : 'string',
          isList: true,
          value: [...value],
        };
      }

      return {
        id,
        name,
        type: 'string',
        isList: true,
        value: value.map((item) => String(item)),
      };
    }

    if (typeof value === 'boolean') {
      return {id, name, type: 'bool', value};
    }
    if (typeof value === 'number' && Number.isFinite(value)) {
      return {id, name, type: 'int', value};
    }
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      return {
        id,
        name,
        type: 'object',
        value: this.objectToJsonEntries(value),
      };
    }
    if (typeof value === 'string' && this.looksLikeUuid(value)) {
      return {id, name, type: 'uuid', value};
    }

    return {id, name, type: 'string', value: value ?? ''};
  }

  private jsonEntriesToObject(entries: JsonFieldEntry[]): Record<string, unknown> {
    const result: Record<string, unknown> = {};
    for (const entry of entries) {
      const key = entry.name.trim();
      if (!key) {
        continue;
      }
      result[key] = this.jsonEntryToValue(entry);
    }
    return result;
  }

  private jsonEntryToValue(entry: JsonFieldEntry): unknown {
    if (entry.isList) {
      if (entry.type === 'object') {
        return this.jsonObjectListItems(entry).map((nested) =>
          this.jsonEntriesToObject(nested),
        );
      }

      const list = this.jsonEntryScalarList(entry);
      switch (entry.type) {
        case 'bool':
          return list.map((value) => Boolean(value));
        case 'int':
          return list
            .map((value) => {
              if (value === '' || value === null || value === undefined) {
                return undefined;
              }
              const numberValue = Number(value);
              return Number.isNaN(numberValue) ? undefined : numberValue;
            })
            .filter((value) => value !== undefined);
        case 'autogenerated_uuid':
        case 'uuid':
        case 'string':
        default:
          return list.map((value) => value ?? '');
      }
    }

    switch (entry.type) {
      case 'bool':
        return Boolean(entry.value);
      case 'int': {
        if (entry.value === '' || entry.value === null || entry.value === undefined) {
          return undefined;
        }
        const numberValue = Number(entry.value);
        return Number.isNaN(numberValue) ? undefined : numberValue;
      }
      case 'object':
        return this.jsonEntriesToObject(
          this.isJsonEntryArray(entry.value) ? entry.value : [],
        );
      case 'autogenerated_uuid':
      case 'uuid':
      case 'string':
      default:
        return entry.value ?? '';
    }
  }

  private createJsonEntry(
    type: JsonConfigurableFieldType = 'string',
  ): JsonFieldEntry {
    return {
      id: this.newJsonEntryId(),
      name: '',
      type,
      value: this.defaultJsonValueForType(type),
    };
  }

  private defaultJsonValueForType(type: JsonConfigurableFieldType): unknown {
    switch (type) {
      case 'bool':
        return false;
      case 'int':
        return '';
      case 'object':
        return [];
      case 'autogenerated_uuid':
        return this.itemFactory.uuid();
      default:
        return '';
    }
  }

  private jsonEntrySingleScalar(entry: JsonFieldEntry): unknown {
    if (entry.type === 'object') {
      return undefined;
    }
    return entry.value;
  }

  private isJsonObjectListValue(value: unknown): value is JsonFieldEntry[][] {
    return (
      Array.isArray(value) &&
      value.every((item) => this.isJsonEntryArray(item))
    );
  }

  private isJsonEntryArray(value: unknown): value is JsonFieldEntry[] {
    return (
      Array.isArray(value) &&
      value.every(
        (item) =>
          !!item &&
          typeof item === 'object' &&
          !Array.isArray(item) &&
          'id' in item &&
          'name' in item &&
          'type' in item,
      )
    );
  }

  private safeParseJsonObject(raw: string): Record<string, unknown> {
    try {
      const parsed = JSON.parse(raw || '{}');
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
        return parsed as Record<string, unknown>;
      }
    } catch {
      // ignore invalid legacy textarea content
    }
    return {};
  }

  private looksLikeUuid(value: string): boolean {
    return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(
      value,
    );
  }

  private newJsonEntryId(): string {
    return `json-${this.itemFactory.uuid()}`;
  }
}
