import {Injectable} from '@angular/core';
import {Directory, DirectoryItem, FieldDefinition} from '../models/directory.models';

@Injectable({providedIn: 'root'})
export class ItemFactoryService {
  createItem(
    directory: Directory,
    raw: Record<string, unknown>,
  ): DirectoryItem {
    const now = new Date().toISOString();
    const data = this.applyGeneratedFields(directory, raw);

    return {
      id: String(data['id']),
      data,
      createdAt: now,
      updatedAt: now,
    };
  }

  applyGeneratedFields(
    directory: Directory,
    raw: Record<string, unknown>,
    options?: {onlyEmpty?: boolean},
  ): Record<string, unknown> {
    const onlyEmpty = options?.onlyEmpty ?? false;
    const data: Record<string, unknown> = {...raw};

    for (const field of directory.schema.fields) {
      if (field.type === 'autogenerated_uuid') {
        if (onlyEmpty && !this.isBlank(data[field.name])) {
          continue;
        }
        if (field.isList) {
          const current = data[field.name];
          data[field.name] =
            Array.isArray(current) && current.length ? current : [this.uuid()];
        } else {
          data[field.name] = this.uuid();
        }
      }

      if (field.type === 'autoincrement') {
        if (onlyEmpty && !this.isBlank(data[field.name])) {
          continue;
        }
        data[field.name] = this.nextAutoincrement(directory, field);
      }

      if (field.type === 'uuid' && this.isBlank(data[field.name])) {
        data[field.name] = this.uuid();
      }
    }

    if (!data['id']) {
      data['id'] = this.uuid();
    }

    return data;
  }

  uuid(): string {
    if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
      return crypto.randomUUID();
    }
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
      const r = (Math.random() * 16) | 0;
      const v = c === 'x' ? r : (r & 0x3) | 0x8;
      return v.toString(16);
    });
  }

  private nextAutoincrement(directory: Directory, field: FieldDefinition): number {
    let max = 0;
    for (const item of directory.items) {
      const value = item.data[field.name];
      const n = typeof value === 'number' ? value : Number(value);
      if (!Number.isNaN(n) && n > max) {
        max = n;
      }
    }
    return max + 1;
  }

  private isBlank(value: unknown): boolean {
    if (value === null || value === undefined || value === '') {
      return true;
    }
    if (typeof value === 'number' && Number.isNaN(value)) {
      return true;
    }
    return Array.isArray(value) && value.length === 0;
  }
}
