import {Injectable} from '@angular/core';
import {Directory, DirectoryItem, FieldDefinition} from '../models/directory.models';

@Injectable({providedIn: 'root'})
export class ItemFactoryService {
  createItem(
    directory: Directory,
    raw: Record<string, unknown>,
  ): DirectoryItem {
    const now = new Date().toISOString();
    const data = this.applyGeneratedFields(directory, raw);

    return {
      id: String(data['id']),
      data,
      createdAt: now,
      updatedAt: now,
    };
  }

  applyGeneratedFields(
    directory: Directory,
    raw: Record<string, unknown>,
  ): Record<string, unknown> {
    const data: Record<string, unknown> = {...raw};

    for (const field of directory.schema.fields) {
      if (field.type === 'autogenerated_uuid') {
        if (field.isList) {
          data[field.name] = Array.isArray(data[field.name])
            ? data[field.name]
            : [this.uuid()];
        } else {
          data[field.name] = this.uuid();
        }
      }

      if (field.type === 'autoincrement') {
        data[field.name] = this.nextAutoincrement(directory, field);
      }

      if (field.type === 'uuid' && (data[field.name] === undefined || data[field.name] === '')) {
        data[field.name] = this.uuid();
      }
    }

    if (!data['id']) {
      data['id'] = this.uuid();
    }

    return data;
  }

  uuid(): string {
    if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
      return crypto.randomUUID();
    }
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
      const r = (Math.random() * 16) | 0;
      const v = c === 'x' ? r : (r & 0x3) | 0x8;
      return v.toString(16);
    });
  }

  private nextAutoincrement(directory: Directory, field: FieldDefinition): number {
    let max = 0;
    for (const item of directory.items) {
      const value = item.data[field.name];
      const n = typeof value === 'number' ? value : Number(value);
      if (!Number.isNaN(n) && n > max) {
        max = n;
      }
    }
    return max + 1;
  }
}
