import {Injectable} from '@angular/core';
import {FieldDefinition, FieldType, FieldValidation} from '../models/directory.models';

@Injectable({providedIn: 'root'})
export class SchemaBuilderService {
  buildJsonSchema(
    fields: FieldDefinition[],
    directoryName: string,
  ): Record<string, unknown> {
    const objectSchema = this.buildObjectShape(fields);

    return {
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      $id: `directory://${directoryName}`,
      title: directoryName,
      ...objectSchema,
    };
  }

  private buildObjectShape(fields: FieldDefinition[]): Record<string, unknown> {
    const properties: Record<string, unknown> = {};
    const required: string[] = [];

    for (const field of fields) {
      const base = this.mapFieldType(field);
      const withValidations = this.applyValidations(base, field.validations, field);
      const property = field.isList
        ? {
            type: 'array',
            description: field.description || undefined,
            items: withValidations,
          }
        : {
            ...withValidations,
            description: field.description || undefined,
          };

      properties[field.name] = property;

      const isRequired =
        field.name === 'id' ||
        field.validations.some((v) => v.kind === 'required');
      if (isRequired) {
        required.push(field.name);
      }
    }

    return {
      type: 'object',
      additionalProperties: false,
      required,
      properties,
    };
  }

  private mapFieldType(field: FieldDefinition): Record<string, unknown> {
    switch (field.type) {
      case 'string':
        return {type: 'string'};
      case 'bool':
        return {type: 'boolean'};
      case 'int':
        return {type: 'number'};
      case 'autoincrement':
        return {type: 'integer'};
      case 'object':
        return this.buildObjectShape(field.fields ?? []);
      case 'json':
        // Free-form per object — structure is not part of the shared schema.
        return {type: 'object', additionalProperties: true};
      case 'enum':
        return {
          type: 'string',
          enum: field.enumValues?.length ? [...field.enumValues] : [],
        };
      case 'uuid':
      case 'autogenerated_uuid':
        return {
          type: 'string',
          format: 'uuid',
          'x-taiga-generated': field.type === 'autogenerated_uuid',
        };
      case 'reference':
        return {
          type: 'string',
          format: 'uuid',
          'x-reference-directory-id': field.referenceDirectoryId || null,
        };
      default:
        return {type: 'string'};
    }
  }

  private applyValidations(
    schema: Record<string, unknown>,
    validations: FieldValidation[],
    field: FieldDefinition,
  ): Record<string, unknown> {
    const next = {...schema};
    const xValidations: Record<string, unknown>[] = [];

    for (const v of validations) {
      switch (v.kind) {
        case 'min':
          if (field.type === 'int' || field.type === 'autoincrement') {
            next['minimum'] = Number(v.value);
          }
          break;
        case 'max':
          if (field.type === 'int' || field.type === 'autoincrement') {
            next['maximum'] = Number(v.value);
          }
          break;
        case 'minLength':
          next['minLength'] = Number(v.value);
          break;
        case 'maxLength':
          next['maxLength'] = Number(v.value);
          break;
        case 'regex':
          next['pattern'] = String(v.value ?? '');
          break;
        case 'unique':
          next['x-unique'] = true;
          break;
        case 'custom':
          xValidations.push({
            kind: 'custom',
            rule: v.customRule,
            message: v.message,
          });
          break;
        case 'server':
          xValidations.push({
            kind: 'server',
            validatorId: v.serverValidatorId,
            message: v.message,
          });
          break;
        default:
          break;
      }
    }

    if (xValidations.length) {
      next['x-validations'] = xValidations;
    }

    return next;
  }

  static readonly systemIdFieldId = 'field-id';

  isSystemIdField(field: Pick<FieldDefinition, 'id'>): boolean {
    return field.id === SchemaBuilderService.systemIdFieldId;
  }

  ensureIdField(fields: FieldDefinition[]): FieldDefinition[] {
    const withoutId = fields.filter((f) => !this.isSystemIdField(f));
    const idField: FieldDefinition = {
      id: SchemaBuilderService.systemIdFieldId,
      name: 'id',
      description: 'Уникальный идентификатор объекта справочника',
      type: 'autogenerated_uuid',
      isList: false,
      validations: [
        {
          id: 'val-id-required',
          kind: 'required',
        },
        {
          id: 'val-id-unique',
          kind: 'unique',
        },
      ],
    };
    return [idField, ...withoutId];
  }

  typeSupportsList(type: FieldType): boolean {
    return !['autoincrement', 'autogenerated_uuid'].includes(type);
  }
}
