import {Injectable} from '@angular/core';
import {
  FieldDefinition,
  FieldType,
  FieldValidation,
  ServerValidatorDescriptor,
} from '../models/directory.models';

/** Mock catalog of server validators that will later come from the backend. */
@Injectable({providedIn: 'root'})
export class ValidationCatalogService {
  readonly validators: ServerValidatorDescriptor[] = [
    {
      id: 'srv.email',
      name: 'Email',
      description: 'Проверка формата email на сервере',
      applicableTypes: ['string'],
    },
    {
      id: 'srv.phone',
      name: 'Телефон',
      description: 'Нормализация и проверка телефона',
      applicableTypes: ['string'],
    },
    {
      id: 'srv.inn',
      name: 'ИНН',
      description: 'Контрольная сумма ИНН',
      applicableTypes: ['string', 'int'],
    },
    {
      id: 'srv.json-schema',
      name: 'JSON Schema',
      description: 'Глубокая валидация JSON по вложенной схеме',
      applicableTypes: ['json'],
    },
    {
      id: 'srv.ref-exists',
      name: 'Ссылка существует',
      description: 'Проверка существования объекта в целевом справочнике',
      applicableTypes: ['reference'],
    },
    {
      id: 'srv.unique-composite',
      name: 'Составная уникальность',
      description: 'Уникальность в сочетании с другими полями',
      applicableTypes: [
        'string',
        'int',
        'uuid',
        'enum',
        'reference',
        'bool',
        'json',
        'autoincrement',
        'autogenerated_uuid',
      ],
    },
  ];

  forType(type: FieldType): ServerValidatorDescriptor[] {
    return this.validators.filter((v) => v.applicableTypes.includes(type));
  }

  byId(id: string): ServerValidatorDescriptor | undefined {
    return this.validators.find((v) => v.id === id);
  }

  labelFor(validation: FieldValidation, field?: FieldDefinition): string {
    switch (validation.kind) {
      case 'required':
        return 'обязательное';
      case 'min':
        return `min ≥ ${validation.value}`;
      case 'max':
        return `max ≤ ${validation.value}`;
      case 'minLength':
        return `длина ≥ ${validation.value}`;
      case 'maxLength':
        return `длина ≤ ${validation.value}`;
      case 'regex':
        return `regex: ${validation.value}`;
      case 'unique':
        return 'уникальное';
      case 'custom':
        return `custom: ${validation.customRule || '—'}`;
      case 'server': {
        const srv = validation.serverValidatorId
          ? this.byId(validation.serverValidatorId)
          : undefined;
        return `server: ${srv?.name || validation.serverValidatorId || '—'}`;
      }
      default:
        return field?.name || validation.kind;
    }
  }
}
