import {JsonPipe, NgTemplateOutlet} from '@angular/common';
import {Component, computed, effect, inject, signal, untracked} from '@angular/core';
import {toSignal} from '@angular/core/rxjs-interop';
import {FormsModule} from '@angular/forms';
import {ActivatedRoute, Router, RouterLink} from '@angular/router';
import {TuiTable, TuiTablePagination} from '@taiga-ui/addon-table';
import {
  TuiButton,
  TuiCell,
  TuiDataList,
  TuiDialog,
  TuiDialogService,
  TuiDropdown,
  TuiHint,
  TuiIcon,
  TuiInput,
  TuiLabel,
  TuiNotification,
  TuiTextfield,
  TuiTitle,
} from '@taiga-ui/core';
import {
  TUI_CONFIRM,
  TuiAccordion,
  TuiBadge,
  TuiChevron,
  TuiChip,
  TuiDataListWrapper,
  TuiFilter,
  TuiInputChip,
  TuiItemsWithMore,
  TuiMultiSelect,
  TuiSelect,
  TuiStatus,
  TuiSwitch,
  TuiTextarea,
} from '@taiga-ui/kit';
import {TuiCardLarge, TuiForm, TuiHeader} from '@taiga-ui/layout';
import {PolymorpheusTemplate} from '@taiga-ui/polymorpheus';
import {map} from 'rxjs';
import {
  DirectoryItem,
  DirectoryType,
  FILE_DIRECTORY_FORMAT_OPTIONS,
  FieldDefinition,
  FieldType,
  FileDirectoryFormat,
  JSON_FIELD_TYPE_OPTIONS,
  JsonConfigurableFieldType,
  JsonFieldEntry,
} from '../../core/models/directory.models';
import {DirectoryStoreService} from '../../core/services/directory-store.service';

type SortDir = 'asc' | 'desc';

const PAGE_SIZES = [10, 25, 50, 100] as const;
const AUTO_GENERATED_HINT =
  'Значение сгенерируется автоматически после создания объекта';

@Component({
  selector: 'app-directory-view',
  standalone: true,
  imports: [
    FormsModule,
    JsonPipe,
    NgTemplateOutlet,
    PolymorpheusTemplate,
    RouterLink,
    TuiAccordion,
    TuiBadge,
    TuiButton,
    TuiCardLarge,
    TuiCell,
    TuiChevron,
    TuiChip,
    TuiDataList,
    TuiDataListWrapper,
    TuiDialog,
    TuiDropdown,
    TuiFilter,
    TuiForm,
    TuiHeader,
    TuiHint,
    TuiIcon,
    TuiInput,
    TuiInputChip,
    TuiItemsWithMore,
    TuiLabel,
    TuiMultiSelect,
    TuiNotification,
    TuiSelect,
    TuiStatus,
    TuiSwitch,
    TuiTable,
    TuiTablePagination,
    TuiTextarea,
    TuiTextfield,
    TuiTitle,
  ],
  templateUrl: './directory-view.component.html',
  styleUrl: './directory-view.component.less',
})
export class DirectoryViewComponent {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly store = inject(DirectoryStoreService);
  private readonly dialogs = inject(TuiDialogService);

  readonly autoGeneratedHint = AUTO_GENERATED_HINT;

  private readonly directoryId = toSignal(
    this.route.paramMap.pipe(map((p) => p.get('id') || '')),
    {initialValue: ''},
  );

  readonly directory = computed(() => {
    const id = this.directoryId();
    return id ? this.store.getDirectory(id) : undefined;
  });

  readonly groupName = computed(() => {
    const dir = this.directory();
    return dir ? this.store.getGroup(dir.groupId)?.name || '—' : '—';
  });

  readonly directoryType = computed<DirectoryType>(
    () => this.directory()?.type ?? 'list',
  );

  readonly isListDirectory = computed(() => this.directoryType() === 'list');
  readonly isSingleDirectory = computed(() => this.directoryType() === 'single');
  readonly isFileDirectory = computed(() => this.directoryType() === 'file');
  readonly isSchemaType = computed(
    () => this.isListDirectory() || this.isSingleDirectory(),
  );

  readonly singleItem = computed(() => this.directory()?.items[0]);

  readonly fileFormatValues = FILE_DIRECTORY_FORMAT_OPTIONS.map((o) => o.value);
  readonly jsonFieldTypeValues = JSON_FIELD_TYPE_OPTIONS.map((o) => o.value);
  readonly fileFormat = signal<FileDirectoryFormat>('json');
  readonly fileContent = signal('');
  readonly fileError = signal('');
  readonly singleFormError = signal('');
  private initialSingleSnapshot = '';
  private initialFileFormat: FileDirectoryFormat = 'json';
  private initialFileContent = '';

  readonly fieldNames = computed(
    () => this.directory()?.schema.fields.map((f) => f.name) ?? [],
  );

  readonly visibleColumns = signal<string[]>([]);
  readonly search = signal('');
  readonly filterField = signal<string | null>(null);
  readonly filterValue = signal('');
  readonly sortField = signal<string>('id');
  readonly sortDir = signal<SortDir>('asc');
  readonly createOpen = signal(false);
  readonly editingItemId = signal<string | null>(null);
  readonly formError = signal('');
  readonly filtersOpen = signal(false);
  readonly columnsOpen = signal(false);
  readonly dirMenuOpen = signal(false);
  readonly contextItemId = signal<string | null>(null);
  readonly expandedObjectKeys = signal<Record<string, boolean>>({});
  readonly jsonEditModes = signal<Record<string, 'configurator' | 'raw'>>({});
  readonly jsonModeErrors = signal<Record<string, string>>({});
  readonly pageSizes = PAGE_SIZES;
  readonly page = signal(0);
  readonly pageSize = signal(10);
  formModel: Record<string, unknown> = {};

  readonly formFields = computed(
    () => this.directory()?.schema.fields ?? [],
  );

  readonly columns = computed(() => {
    const fields = this.directory()?.schema.fields ?? [];
    const selected = this.visibleColumns();
    return selected.length
      ? fields.filter((f) => selected.includes(f.name))
      : fields;
  });

  readonly columnNames = computed(() => this.columns().map((f) => f.name));

  readonly itemDialogTitle = computed(() =>
    this.editingItemId() ? 'Редактирование объекта' : 'Новый объект',
  );

  readonly hasFieldFilter = computed(
    () => Boolean(this.filterField() && this.filterValue().trim()),
  );

  readonly columnLayout = computed(() => {
    const fields = this.columns();
    const items = this.filteredItems();
    const widthsPx = fields.map((field) => {
      let maxLen = Math.max(field.name.length, 8);
      for (const item of items.slice(0, 80)) {
        maxLen = Math.max(maxLen, this.cellValue(item, field).length);
      }
      return Math.max(160, Math.min(40, maxLen) * 9);
    });
    const widthPx = widthsPx.reduce((sum, width) => sum + width, 0);
    return {
      widths: widthsPx.map((width) => `${width}px`),
      width: `${widthPx}px`,
    };
  });

  readonly filteredItems = computed(() => {
    const dir = this.directory();
    if (!dir) {
      return [];
    }

    let items = [...dir.items];
    const q = this.search().trim().toLowerCase();
    if (q) {
      items = items.filter((item) =>
        Object.values(item.data).some((value) =>
          this.stringifyValue(value).toLowerCase().includes(q),
        ),
      );
    }

    const field = this.filterField();
    const filterValue = this.filterValue().trim().toLowerCase();
    if (field && filterValue) {
      items = items.filter((item) =>
        this.stringifyValue(item.data[field])
          .toLowerCase()
          .includes(filterValue),
      );
    }

    const sortField = this.sortField();
    const dirOrder = this.sortDir() === 'asc' ? 1 : -1;
    items.sort((a, b) => {
      const av = this.stringifyValue(a.data[sortField]);
      const bv = this.stringifyValue(b.data[sortField]);
      return av.localeCompare(bv, undefined, {numeric: true}) * dirOrder;
    });

    return items;
  });

  readonly pagedItems = computed(() => {
    const items = this.filteredItems();
    const size = this.pageSize();
    const maxPage = Math.max(0, Math.ceil(items.length / size) - 1);
    const page = Math.min(this.page(), maxPage);
    return items.slice(page * size, page * size + size);
  });

  constructor() {
    effect(() => {
      const dir = this.directory();
      const type = this.directoryType();
      untracked(() => {
        if (!dir || (type !== 'single' && type !== 'file') || dir.items.length) {
          return;
        }
        this.store.addItem(
          dir.id,
          type === 'file' ? {format: dir.fileFormat ?? 'json', content: ''} : {},
        );
      });
    });

    effect(() => {
      const dir = this.directory();
      const type = this.directoryType();
      const item = this.singleItem();
      untracked(() => {
        if (!dir || type !== 'file') {
          return;
        }
        this.fileFormat.set(
          (item?.data['format'] as FileDirectoryFormat) ?? dir.fileFormat ?? 'json',
        );
        this.fileContent.set(String(item?.data['content'] ?? ''));
        this.initialFileFormat = this.fileFormat();
        this.initialFileContent = this.fileContent();
        this.fileError.set('');
      });
    });

    effect(() => {
      const type = this.directoryType();
      const item = this.singleItem();
      untracked(() => {
        if (type !== 'single') {
          return;
        }
        this.populateFormModel(item);
        this.initialSingleSnapshot = this.formSnapshot();
        this.singleFormError.set('');
      });
    });

    effect(() => {
      const id = this.directoryId();
      untracked(() => {
        const dir = id ? this.store.getDirectory(id) : undefined;
        if (!dir) {
          return;
        }
        this.visibleColumns.set(dir.schema.fields.map((f) => f.name));
        this.sortField.set('id');
        this.page.set(0);
      });
    });

    effect(() => {
      this.search();
      this.filterField();
      this.filterValue();
      untracked(() => this.page.set(0));
    });

    effect(() => {
      const total = this.filteredItems().length;
      const size = this.pageSize();
      const maxPage = Math.max(0, Math.ceil(total / size) - 1);
      if (this.page() > maxPage) {
        untracked(() => this.page.set(maxPage));
      }
    });
  }

  openCreate(): void {
    if (!this.directory()) {
      void this.router.navigate(['/']);
      return;
    }

    this.editingItemId.set(null);
    this.formError.set('');
    this.populateFormModel();
    this.createOpen.set(true);
  }

  openEdit(item: DirectoryItem): void {
    if (!this.directory()) {
      return;
    }

    this.editingItemId.set(item.id);
    this.formError.set('');
    this.populateFormModel(item);
    this.createOpen.set(true);
  }

  editContextItem(): void {
    const item = this.contextItem();
    if (item) {
      this.openEdit(item);
    }
  }

  deleteContextItem(): void {
    const itemId = this.contextItemId();
    if (!itemId) {
      return;
    }
    this.deleteItem(itemId);
    this.contextItemId.set(null);
  }

  private contextItem(): DirectoryItem | undefined {
    const itemId = this.contextItemId();
    if (!itemId) {
      return undefined;
    }
    return this.directory()?.items.find((item) => item.id === itemId);
  }

  autoFieldValue(field: FieldDefinition): string {
    if (!this.editingItemId()) {
      return '';
    }
    return this.stringifyValue(this.formModel[field.name]);
  }

  editDirectory(): void {
    const dir = this.directory();
    if (!dir) {
      return;
    }
    void this.router.navigate(['/directories', dir.id, 'edit']);
  }

  deleteDirectory(): void {
    const dir = this.directory();
    if (!dir) {
      return;
    }
    this.dialogs
      .open<boolean>(TUI_CONFIRM, {
        label: `Удалить «${dir.name}»?`,
        size: 's',
        data: {
          content:
            'Справочник и все его объекты будут удалены без возможности восстановления.',
          yes: 'Удалить',
          no: 'Отмена',
          appearance: 'negative',
        },
      })
      .subscribe((confirmed) => {
        if (!confirmed) {
          return;
        }
        this.store.deleteDirectory(dir.id);
        void this.router.navigate(['/']);
      });
  }

  onColumnsChange(columns: readonly string[]): void {
    if (!columns.length) {
      return;
    }
    this.visibleColumns.set([...columns]);
  }

  clearFilter(): void {
    this.filterField.set(null);
    this.filterValue.set('');
  }

  toggleSort(field: string): void {
    if (this.sortField() === field) {
      this.sortDir.update((d) => (d === 'asc' ? 'desc' : 'asc'));
    } else {
      this.sortField.set(field);
      this.sortDir.set('asc');
    }
  }

  cellValue(item: DirectoryItem, field: FieldDefinition): string {
    return this.stringifyValue(item.data[field.name]);
  }

  singleCellValue(field: FieldDefinition): string {
    const item = this.singleItem();
    return item ? this.cellValue(item, field) : '';
  }

  cellList(item: DirectoryItem, field: FieldDefinition): string[] {
    const value = item.data[field.name];
    if (Array.isArray(value)) {
      return value.map((v) => this.stringifyValue(v)).filter(Boolean);
    }
    const text = this.stringifyValue(value);
    return text ? [text] : [];
  }

  isListCell(item: DirectoryItem, field: FieldDefinition): boolean {
    return field.isList || Array.isArray(item.data[field.name]);
  }

  isBoolCell(field: FieldDefinition): boolean {
    return field.type === 'bool' && !field.isList;
  }

  boolValue(item: DirectoryItem, field: FieldDefinition): boolean {
    return Boolean(item.data[field.name]);
  }

  isEmptyCell(item: DirectoryItem, field: FieldDefinition): boolean {
    const value = item.data[field.name];
    if (Array.isArray(value)) {
      return !value.length;
    }
    return value === null || value === undefined || value === '';
  }

  referenceOptions(field: FieldDefinition): string[] {
    if (!field.referenceDirectoryId) {
      return [];
    }
    return (
      this.store
        .getDirectory(field.referenceDirectoryId)
        ?.items.map((i) => i.id) || []
    );
  }

  enumOrRefItems(field: FieldDefinition): string[] {
    return field.type === 'enum'
      ? field.enumValues || []
      : this.referenceOptions(field);
  }

  stringifyRef = (id: string): string => {
    for (const dir of this.store.directories()) {
      const item = dir.items.find((i) => i.id === id);
      if (item) {
        const label =
          (item.data['name'] as string) ||
          (item.data['title'] as string) ||
          id;
        return `${label} (${id.slice(0, 8)}…)`;
      }
    }
    return id;
  };

  stringifyIdentity = (value: string): string => value;

  stringifyFileFormat = (value: FileDirectoryFormat): string =>
    FILE_DIRECTORY_FORMAT_OPTIONS.find((o) => o.value === value)?.label || value;

  stringifyJsonFieldType = (value: JsonConfigurableFieldType): string =>
    JSON_FIELD_TYPE_OPTIONS.find((o) => o.value === value)?.label || value;

  saveSingleItem(): void {
    this.singleFormError.set('');
    const error = this.persistFormModel(this.singleItem()?.id ?? null);
    if (error) {
      this.singleFormError.set(error);
    }
  }

  cancelSingleItemChanges(): void {
    this.populateFormModel(this.singleItem());
    this.singleFormError.set('');
  }

  hasSingleChanges(): boolean {
    return this.formSnapshot() !== this.initialSingleSnapshot;
  }

  saveFile(): void {
    const dir = this.directory();
    if (!dir || this.directoryType() !== 'file') {
      return;
    }

    this.fileError.set('');
    const format = this.fileFormat();
    const content = this.fileContent();

    if (format === 'json' && content.trim()) {
      try {
        JSON.parse(content);
      } catch {
        this.fileError.set('Невалидный JSON');
        return;
      }
    }

    const item = this.singleItem();
    const payload = {format, content};
    if (item) {
      this.store.updateItem(dir.id, item.id, payload);
    } else {
      this.store.addItem(dir.id, payload);
    }

    this.store.updateDirectory(dir.id, {
      name: dir.name,
      description: dir.description,
      type: dir.type,
      fileFormat: format,
      fileSchemaEnabled: dir.fileSchemaEnabled,
      fileSchemaText: dir.fileSchemaText,
      schema: dir.schema,
    });

    this.initialFileFormat = format;
    this.initialFileContent = content;
  }

  cancelFileChanges(): void {
    this.fileFormat.set(this.initialFileFormat);
    this.fileContent.set(this.initialFileContent);
    this.fileError.set('');
  }

  hasFileChanges(): boolean {
    return (
      this.fileFormat() !== this.initialFileFormat ||
      this.fileContent() !== this.initialFileContent
    );
  }

  saveItem(observer: {complete: () => void}): void {
    this.formError.set('');
    const error = this.persistFormModel(this.editingItemId());
    if (error) {
      this.formError.set(error);
      return;
    }
    this.editingItemId.set(null);
    this.createOpen.set(false);
    observer.complete();
  }

  deleteCurrentItem(observer: {complete: () => void}): void {
    if (this.directoryType() !== 'list') {
      observer.complete();
      return;
    }
    const itemId = this.editingItemId();
    if (!itemId) {
      return;
    }
    this.deleteItem(itemId);
    this.editingItemId.set(null);
    this.createOpen.set(false);
    observer.complete();
  }

  deleteItem(itemId: string): void {
    if (this.directoryType() !== 'list') {
      return;
    }
    const dir = this.directory();
    if (!dir) {
      return;
    }
    this.store.deleteItem(dir.id, itemId);
  }

  isAutoField(type: FieldType): boolean {
    return type === 'autogenerated_uuid' || type === 'autoincrement';
  }

  private stringifyValue(value: unknown): string {
    if (value === null || value === undefined) {
      return '';
    }
    if (typeof value === 'object') {
      return JSON.stringify(value);
    }
    return String(value);
  }

  fieldValue(container: Record<string, unknown>, field: FieldDefinition): unknown {
    return container[field.name];
  }

  setFieldValue(
    container: Record<string, unknown>,
    field: FieldDefinition,
    value: unknown,
  ): void {
    container[field.name] = value;
  }

  objectPath(basePath: string, segment: string): string {
    return basePath ? `${basePath}.${segment}` : segment;
  }

  listObjectPath(basePath: string, index: number): string {
    return `${basePath}[${index}]`;
  }

  isObjectExpanded(path: string): boolean {
    const state = this.expandedObjectKeys();
    return state[path] ?? true;
  }

  toggleObjectExpanded(path: string): void {
    this.expandedObjectKeys.update((state) => ({
      ...state,
      [path]: !(state[path] ?? true),
    }));
  }

  objectValue(
    container: Record<string, unknown>,
    field: FieldDefinition,
  ): Record<string, unknown> {
    const current = container[field.name];
    if (current && typeof current === 'object' && !Array.isArray(current)) {
      return current as Record<string, unknown>;
    }
    const next = this.defaultObjectValue(field);
    container[field.name] = next;
    return next;
  }

  objectListValue(
    container: Record<string, unknown>,
    field: FieldDefinition,
  ): Record<string, unknown>[] {
    const current = container[field.name];
    if (Array.isArray(current)) {
      return current.filter(
        (item) => item && typeof item === 'object' && !Array.isArray(item),
      ) as Record<string, unknown>[];
    }
    const next: Record<string, unknown>[] = [];
    container[field.name] = next;
    return next;
  }

  addObjectListItem(container: Record<string, unknown>, field: FieldDefinition): void {
    const list = this.objectListValue(container, field);
    list.push(this.defaultObjectValue(field));
    container[field.name] = [...list];
  }

  removeObjectListItem(
    container: Record<string, unknown>,
    field: FieldDefinition,
    index: number,
  ): void {
    const list = this.objectListValue(container, field).filter((_, i) => i !== index);
    container[field.name] = list;
  }

  jsonEntries(
    container: Record<string, unknown>,
    field: FieldDefinition,
  ): JsonFieldEntry[] {
    const current = container[field.name];
    if (this.isJsonEntryArray(current)) {
      return current;
    }
    const next = this.objectToJsonEntries(
      typeof current === 'string' ? this.safeParseJsonObject(current) : current,
    );
    container[field.name] = next;
    return next;
  }

  jsonListValue(
    container: Record<string, unknown>,
    field: FieldDefinition,
  ): unknown[] {
    const current = container[field.name];
    if (Array.isArray(current)) {
      return current;
    }
    const next: unknown[] = [];
    container[field.name] = next;
    return next;
  }

  jsonListItemEntries(
    container: Record<string, unknown>,
    field: FieldDefinition,
    index: number,
  ): JsonFieldEntry[] {
    const list = [...this.jsonListValue(container, field)];
    const item = list[index];
    if (this.isJsonEntryArray(item)) {
      return item;
    }
    const next = this.objectToJsonEntries(
      typeof item === 'string' ? this.safeParseJsonObject(item) : item,
    );
    list[index] = next;
    container[field.name] = list;
    return next;
  }

  jsonListItemRawText(
    container: Record<string, unknown>,
    field: FieldDefinition,
    index: number,
  ): string {
    const item = this.jsonListValue(container, field)[index];
    if (typeof item === 'string') {
      return item;
    }
    const obj = this.isJsonEntryArray(item)
      ? this.jsonEntriesToObject(item)
      : this.coerceJsonObject(item);
    return JSON.stringify(obj, null, 2);
  }

  setJsonListItemRawText(
    container: Record<string, unknown>,
    field: FieldDefinition,
    index: number,
    path: string,
    text: string,
  ): void {
    const list = [...this.jsonListValue(container, field)];
    list[index] = text;
    container[field.name] = list;
    this.clearJsonModeError(path);
  }

  addJsonListItem(container: Record<string, unknown>, field: FieldDefinition): void {
    const list = this.jsonListValue(container, field);
    container[field.name] = [...list, []];
  }

  removeJsonListItem(
    container: Record<string, unknown>,
    field: FieldDefinition,
    index: number,
  ): void {
    container[field.name] = this.jsonListValue(container, field).filter(
      (_, i) => i !== index,
    );
  }

  isJsonRawMode(path: string): boolean {
    return (this.jsonEditModes()[path] ?? 'configurator') === 'raw';
  }

  jsonModeError(path: string): string {
    return this.jsonModeErrors()[path] ?? '';
  }

  setFieldJsonRawMode(
    container: Record<string, unknown>,
    field: FieldDefinition,
    path: string,
    raw: boolean,
  ): void {
    this.applyJsonRawMode(
      path,
      raw,
      () => container[field.name],
      (value) => {
        container[field.name] = value;
      },
    );
  }

  setJsonFieldRawText(
    container: Record<string, unknown>,
    field: FieldDefinition,
    path: string,
    text: string,
  ): void {
    container[field.name] = text;
    this.clearJsonModeError(path);
  }

  setJsonListItemRawMode(
    container: Record<string, unknown>,
    field: FieldDefinition,
    index: number,
    path: string,
    raw: boolean,
  ): void {
    this.applyJsonRawMode(
      path,
      raw,
      () => this.jsonListValue(container, field)[index],
      (value) => {
        const list = [...this.jsonListValue(container, field)];
        list[index] = value;
        container[field.name] = list;
      },
    );
  }

  addJsonEntry(entries: JsonFieldEntry[]): void {
    entries.push(this.createJsonEntry());
  }

  removeJsonEntry(entries: JsonFieldEntry[], index: number): void {
    entries.splice(index, 1);
  }

  nestedJsonEntries(entry: JsonFieldEntry): JsonFieldEntry[] {
    if (this.isJsonEntryArray(entry.value)) {
      return entry.value;
    }
    const next = this.objectToJsonEntries(entry.value);
    entry.value = next;
    return next;
  }

  onJsonEntryTypeChange(
    entry: JsonFieldEntry,
    type: JsonConfigurableFieldType,
  ): void {
    entry.type = type;
    entry.value = this.defaultJsonValueForType(type);
    if (type === 'enum') {
      entry.enumValues = entry.enumValues?.length ? [...entry.enumValues] : [];
    } else {
      delete entry.enumValues;
    }
  }

  setJsonEntryEnumValues(entry: JsonFieldEntry, values: string[]): void {
    entry.enumValues = values;
    if (entry.value && !values.includes(String(entry.value))) {
      entry.value = '';
    }
  }

  private applyJsonRawMode(
    path: string,
    raw: boolean,
    getValue: () => unknown,
    setValue: (value: unknown) => void,
  ): void {
    const currentMode = this.jsonEditModes()[path] ?? 'configurator';
    const nextMode = raw ? 'raw' : 'configurator';
    if (currentMode === nextMode) {
      return;
    }

    if (raw) {
      const current = getValue();
      const obj = this.isJsonEntryArray(current)
        ? this.jsonEntriesToObject(current)
        : this.coerceJsonObject(current);
      setValue(JSON.stringify(obj, null, 2));
      this.clearJsonModeError(path);
      this.jsonEditModes.update((modes) => ({...modes, [path]: 'raw'}));
      return;
    }

    const current = getValue();
    if (typeof current === 'string') {
      const parsed = this.tryParseJsonObject(current);
      if (parsed.error) {
        this.jsonModeErrors.update((errors) => ({
          ...errors,
          [path]: parsed.error!,
        }));
        return;
      }
      setValue(this.objectToJsonEntries(parsed.value ?? {}));
    } else {
      setValue(this.objectToJsonEntries(this.coerceJsonObject(current)));
    }

    this.clearJsonModeError(path);
    this.jsonEditModes.update((modes) => ({...modes, [path]: 'configurator'}));
  }

  private clearJsonModeError(path: string): void {
    this.jsonModeErrors.update((errors) => {
      if (!errors[path]) {
        return errors;
      }
      const next = {...errors};
      delete next[path];
      return next;
    });
  }

  private coerceJsonObject(value: unknown): Record<string, unknown> {
    if (typeof value === 'string') {
      return this.safeParseJsonObject(value);
    }
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      return value as Record<string, unknown>;
    }
    return {};
  }

  private tryParseJsonObject(
    raw: string,
  ): {value?: Record<string, unknown>; error?: string} {
    try {
      const parsed = JSON.parse(raw || '{}');
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
        return {value: parsed as Record<string, unknown>};
      }
      return {error: 'JSON должен быть объектом {...}'};
    } catch {
      return {error: 'Невалидный JSON'};
    }
  }

  private populateFormModel(item?: DirectoryItem): void {
    this.formModel = {};
    this.jsonEditModes.set({});
    this.jsonModeErrors.set({});
    for (const field of this.formFields()) {
      const value = item?.data[field.name];
      if (this.isAutoField(field.type)) {
        this.formModel[field.name] = value ?? '';
        continue;
      }
      if (field.isList) {
        if (field.type === 'object') {
          this.formModel[field.name] = this.prepareObjectListValue(field, value);
        } else if (field.type === 'json') {
          this.formModel[field.name] = Array.isArray(value)
            ? value.map((itemValue) => this.objectToJsonEntries(itemValue))
            : [];
        } else {
          this.formModel[field.name] = Array.isArray(value) ? [...value] : [];
        }
      } else if (field.type === 'json') {
        this.formModel[field.name] = this.objectToJsonEntries(
          typeof value === 'string' ? this.safeParseJsonObject(value) : value,
        );
      } else if (field.type === 'object') {
        this.formModel[field.name] = this.prepareObjectValue(field, value);
      } else if (field.type === 'bool') {
        this.formModel[field.name] = Boolean(value);
      } else {
        this.formModel[field.name] = value ?? '';
      }
    }
  }

  private persistFormModel(editingId: string | null): string | null {
    const dir = this.directory();
    if (!dir) {
      return 'Справочник не найден';
    }

    const payload: Record<string, unknown> = {};
    for (const field of dir.schema.fields) {
      if (this.isAutoField(field.type) && field.type !== 'uuid') {
        if (editingId) {
          payload[field.name] = this.formModel[field.name];
        }
        continue;
      }

      const normalized = this.normalizeFieldValue(
        field,
        this.formModel[field.name],
        field.name,
      );
      if (normalized.error) {
        return normalized.error;
      }
      const value = normalized.value;
      if (field.validations.some((v) => v.kind === 'required')) {
        const emptyList = field.isList && Array.isArray(value) && !value.length;
        const emptyScalar =
          !field.isList &&
          (value === undefined || value === null || value === '');
        if (emptyList || emptyScalar) {
          return `Поле «${field.name}» обязательно`;
        }
      }
      payload[field.name] = value;
    }

    if (editingId) {
      this.store.updateItem(dir.id, editingId, payload);
    } else {
      this.store.addItem(dir.id, payload);
    }
    this.initialSingleSnapshot = this.formSnapshot();
    return null;
  }

  private formSnapshot(): string {
    const normalized = this.formFields().map((field) => ({
      name: field.name,
      value: this.formModel[field.name] ?? null,
    }));
    return JSON.stringify(normalized);
  }

  private prepareObjectValue(
    field: FieldDefinition,
    value: unknown,
  ): Record<string, unknown> {
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      return this.hydrateObjectBySchema(field, value as Record<string, unknown>);
    }
    return this.defaultObjectValue(field);
  }

  private prepareObjectListValue(
    field: FieldDefinition,
    value: unknown,
  ): Record<string, unknown>[] {
    if (!Array.isArray(value)) {
      return [];
    }
    return value
      .filter((item) => item && typeof item === 'object' && !Array.isArray(item))
      .map((item) => this.hydrateObjectBySchema(field, item as Record<string, unknown>));
  }

  private defaultObjectValue(field: FieldDefinition): Record<string, unknown> {
    const result: Record<string, unknown> = {};
    for (const child of field.fields ?? []) {
      result[child.name] = this.defaultValueForField(child);
    }
    return result;
  }

  private hydrateObjectBySchema(
    field: FieldDefinition,
    source: Record<string, unknown>,
  ): Record<string, unknown> {
    const result: Record<string, unknown> = {};
    for (const child of field.fields ?? []) {
      const value = source[child.name];
      if (child.type === 'object' && child.isList) {
        result[child.name] = this.prepareObjectListValue(child, value);
      } else if (child.type === 'object') {
        result[child.name] = this.prepareObjectValue(child, value);
      } else if (child.type === 'json' && child.isList) {
        result[child.name] = Array.isArray(value)
          ? value.map((itemValue) => this.objectToJsonEntries(itemValue))
          : [];
      } else if (child.type === 'json') {
        result[child.name] = this.objectToJsonEntries(
          typeof value === 'string' ? this.safeParseJsonObject(value) : value,
        );
      } else if (child.isList) {
        result[child.name] = Array.isArray(value) ? [...value] : [];
      } else if (child.type === 'bool') {
        result[child.name] = Boolean(value);
      } else {
        result[child.name] = value ?? this.defaultValueForField(child);
      }
    }
    return result;
  }

  private defaultValueForField(field: FieldDefinition): unknown {
    if (field.type === 'object') {
      return field.isList ? [] : this.defaultObjectValue(field);
    }
    if (field.type === 'json') {
      return [];
    }
    if (field.isList) {
      return [];
    }
    if (field.type === 'bool') {
      return false;
    }
    return '';
  }

  private normalizeFieldValue(
    field: FieldDefinition,
    rawValue: unknown,
    path: string,
  ): {value: unknown; error?: string} {
    if (field.isList) {
      const list = Array.isArray(rawValue) ? rawValue : [];
      const values: unknown[] = [];
      for (let i = 0; i < list.length; i++) {
        const itemResult = this.normalizeSingleFieldValue(
          {...field, isList: false},
          list[i],
          `${path}[${i}]`,
        );
        if (itemResult.error) {
          return itemResult;
        }
        values.push(itemResult.value);
      }
      return {value: values};
    }
    return this.normalizeSingleFieldValue(field, rawValue, path);
  }

  private normalizeSingleFieldValue(
    field: FieldDefinition,
    rawValue: unknown,
    path: string,
  ): {value: unknown; error?: string} {
    if (field.type === 'int') {
      if (rawValue === '' || rawValue === null || rawValue === undefined) {
        return {value: undefined};
      }
      const numberValue = Number(rawValue);
      if (Number.isNaN(numberValue)) {
        return {value: undefined, error: `Поле «${path}»: ожидается число`};
      }
      return {value: numberValue};
    }

    if (field.type === 'json') {
      return this.normalizeJsonEntries(rawValue, path);
    }

    if (field.type === 'object') {
      if (!rawValue || typeof rawValue !== 'object' || Array.isArray(rawValue)) {
        return {value: this.defaultObjectValue(field)};
      }
      const source = rawValue as Record<string, unknown>;
      const result: Record<string, unknown> = {};
      for (const child of field.fields ?? []) {
        const childResult = this.normalizeFieldValue(
          child,
          source[child.name],
          `${path}.${child.name}`,
        );
        if (childResult.error) {
          return childResult;
        }
        const childValue = childResult.value;
        if (child.validations.some((v) => v.kind === 'required')) {
          const emptyList = child.isList && Array.isArray(childValue) && !childValue.length;
          const emptyScalar =
            !child.isList &&
            (childValue === undefined || childValue === null || childValue === '');
          if (emptyList || emptyScalar) {
            return {value: undefined, error: `Поле «${path}.${child.name}» обязательно`};
          }
        }
        result[child.name] = childValue;
      }
      return {value: result};
    }

    if (field.type === 'bool') {
      return {value: Boolean(rawValue)};
    }

    return {value: rawValue};
  }

  private normalizeJsonEntries(
    rawValue: unknown,
    path: string,
  ): {value: Record<string, unknown>; error?: string} {
    if (typeof rawValue === 'string') {
      const parsed = this.tryParseJsonObject(rawValue);
      if (parsed.error) {
        return {value: {}, error: `Поле «${path}»: ${parsed.error}`};
      }
      return {value: parsed.value ?? {}};
    }

    if (!Array.isArray(rawValue)) {
      if (rawValue && typeof rawValue === 'object' && !Array.isArray(rawValue)) {
        return {value: rawValue as Record<string, unknown>};
      }
      return {value: {}};
    }

    if (!this.isJsonEntryArray(rawValue)) {
      return {value: {}};
    }

    const entries = rawValue;
    const names = new Set<string>();

    for (const entry of entries) {
      const name = entry.name?.trim() ?? '';
      if (!name) {
        return {
          value: {},
          error: `Поле «${path}»: укажите название для всех ключей`,
        };
      }
      if (names.has(name)) {
        return {
          value: {},
          error: `Поле «${path}»: дублируется ключ «${name}»`,
        };
      }
      names.add(name);

      if (entry.type === 'int') {
        if (entry.value === '' || entry.value === null || entry.value === undefined) {
          continue;
        }
        if (Number.isNaN(Number(entry.value))) {
          return {
            value: {},
            error: `Поле «${path}.${name}»: ожидается число`,
          };
        }
      }

      if (entry.type === 'object' || entry.type === 'json') {
        const nested = this.normalizeJsonEntries(
          entry.value,
          `${path}.${name}`,
        );
        if (nested.error) {
          return nested;
        }
      }
    }

    return {value: this.jsonEntriesToObject(entries)};
  }

  private objectToJsonEntries(source: unknown): JsonFieldEntry[] {
    if (!source || typeof source !== 'object' || Array.isArray(source)) {
      return [];
    }

    return Object.entries(source as Record<string, unknown>).map(([name, value]) =>
      this.valueToJsonEntry(name, value),
    );
  }

  private valueToJsonEntry(name: string, value: unknown): JsonFieldEntry {
    const id = this.newJsonEntryId();

    if (typeof value === 'boolean') {
      return {id, name, type: 'bool', value};
    }
    if (typeof value === 'number' && Number.isFinite(value)) {
      return {id, name, type: 'int', value};
    }
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      return {
        id,
        name,
        type: 'object',
        value: this.objectToJsonEntries(value),
      };
    }
    if (Array.isArray(value)) {
      return {id, name, type: 'string', value: JSON.stringify(value)};
    }
    if (typeof value === 'string' && this.looksLikeUuid(value)) {
      return {id, name, type: 'uuid', value};
    }

    return {id, name, type: 'string', value: value ?? ''};
  }

  private jsonEntriesToObject(entries: JsonFieldEntry[]): Record<string, unknown> {
    const result: Record<string, unknown> = {};
    for (const entry of entries) {
      const key = entry.name.trim();
      if (!key) {
        continue;
      }
      result[key] = this.jsonEntryToValue(entry);
    }
    return result;
  }

  private jsonEntryToValue(entry: JsonFieldEntry): unknown {
    switch (entry.type) {
      case 'bool':
        return Boolean(entry.value);
      case 'int': {
        if (entry.value === '' || entry.value === null || entry.value === undefined) {
          return undefined;
        }
        const numberValue = Number(entry.value);
        return Number.isNaN(numberValue) ? undefined : numberValue;
      }
      case 'object':
      case 'json':
        return this.jsonEntriesToObject(
          this.isJsonEntryArray(entry.value) ? entry.value : [],
        );
      case 'autogenerated_uuid':
      case 'uuid':
      case 'enum':
      case 'string':
      default:
        return entry.value ?? '';
    }
  }

  private createJsonEntry(
    type: JsonConfigurableFieldType = 'string',
  ): JsonFieldEntry {
    const entry: JsonFieldEntry = {
      id: this.newJsonEntryId(),
      name: '',
      type,
      value: this.defaultJsonValueForType(type),
    };
    if (type === 'enum') {
      entry.enumValues = [];
    }
    return entry;
  }

  private defaultJsonValueForType(type: JsonConfigurableFieldType): unknown {
    switch (type) {
      case 'bool':
        return false;
      case 'int':
        return '';
      case 'object':
      case 'json':
        return [];
      case 'autogenerated_uuid':
        return this.newUuid();
      default:
        return '';
    }
  }

  private isJsonEntryArray(value: unknown): value is JsonFieldEntry[] {
    return (
      Array.isArray(value) &&
      value.every(
        (item) =>
          !!item &&
          typeof item === 'object' &&
          !Array.isArray(item) &&
          'id' in item &&
          'name' in item &&
          'type' in item,
      )
    );
  }

  private safeParseJsonObject(raw: string): Record<string, unknown> {
    try {
      const parsed = JSON.parse(raw || '{}');
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
        return parsed as Record<string, unknown>;
      }
    } catch {
      // ignore invalid legacy textarea content
    }
    return {};
  }

  private looksLikeUuid(value: string): boolean {
    return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(
      value,
    );
  }

  private newJsonEntryId(): string {
    return `json-${this.newUuid()}`;
  }

  private newUuid(): string {
    if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
      return crypto.randomUUID();
    }
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
      const r = (Math.random() * 16) | 0;
      const v = c === 'x' ? r : (r & 0x3) | 0x8;
      return v.toString(16);
    });
  }
}
