export type FieldType =
  | 'string'
  | 'bool'
  | 'int'
  | 'object'
  | 'json'
  | 'enum'
  | 'autoincrement'
  | 'uuid'
  | 'autogenerated_uuid'
  | 'reference';

export type ValidationKind =
  | 'required'
  | 'min'
  | 'max'
  | 'minLength'
  | 'maxLength'
  | 'regex'
  | 'unique'
  | 'custom'
  | 'server';

export interface FieldValidation {
  id: string;
  kind: ValidationKind;
  value?: string | number;
  message?: string;
  /** Id of server-side validator from backend catalog */
  serverValidatorId?: string;
  /** Free-form custom rule description / expression */
  customRule?: string;
}

export interface FieldDefinition {
  id: string;
  name: string;
  description: string;
  type: FieldType;
  isList: boolean;
  fields?: FieldDefinition[];
  enumValues?: string[];
  referenceDirectoryId?: string;
  validations: FieldValidation[];
}

export interface DirectorySchema {
  fields: FieldDefinition[];
  jsonSchema: unknown;
}

export type DirectoryType = 'list' | 'single' | 'file';
export type FileDirectoryFormat = 'json' | 'yaml';

export interface DirectoryItem {
  id: string;
  data: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
}

export interface Directory {
  id: string;
  groupId: string;
  name: string;
  description: string;
  type: DirectoryType;
  fileFormat?: FileDirectoryFormat;
  fileSchemaEnabled?: boolean;
  fileSchemaText?: string;
  schema: DirectorySchema;
  items: DirectoryItem[];
  createdAt: string;
  updatedAt: string;
}

export interface DirectoryGroup {
  id: string;
  name: string;
  order: number;
}

export interface ServerValidatorDescriptor {
  id: string;
  name: string;
  description: string;
  applicableTypes: FieldType[];
}

export interface AppStoreState {
  groups: DirectoryGroup[];
  directories: Directory[];
}

export const FIELD_TYPE_OPTIONS: ReadonlyArray<{ value: FieldType; label: string }> = [
  {value: 'string', label: 'Строка (string)'},
  {value: 'bool', label: 'Булево (bool)'},
  {value: 'int', label: 'Число (number)'},
  {value: 'object', label: 'Объект (object)'},
  {value: 'json', label: 'JSON'},
  {value: 'enum', label: 'Перечисление (enum)'},
  {value: 'autoincrement', label: 'Автоинкремент'},
  {value: 'uuid', label: 'UUID (ручной)'},
  {value: 'autogenerated_uuid', label: 'UUID (автогенерация)'},
  {value: 'reference', label: 'Ссылка на справочник'},
];

/** Types allowed inside a free-form JSON field configurator (per-object, not schema). */
export type JsonConfigurableFieldType = Exclude<
  FieldType,
  'autoincrement' | 'reference' | 'json' | 'enum'
>;

export interface JsonFieldEntry {
  id: string;
  name: string;
  type: JsonConfigurableFieldType;
  isList?: boolean;
  /** Nested entries for object; scalar or list values otherwise. */
  value: unknown;
}

export const JSON_FIELD_TYPE_OPTIONS: ReadonlyArray<{
  value: JsonConfigurableFieldType;
  label: string;
}> = FIELD_TYPE_OPTIONS.filter(
  (o): o is {value: JsonConfigurableFieldType; label: string} =>
    o.value !== 'autoincrement' &&
    o.value !== 'reference' &&
    o.value !== 'json' &&
    o.value !== 'enum',
);

export const VALIDATION_KIND_OPTIONS: ReadonlyArray<{
  value: ValidationKind;
  label: string;
}> = [
  {value: 'required', label: 'Обязательное'},
  {value: 'min', label: 'Минимум (число)'},
  {value: 'max', label: 'Максимум (число)'},
  {value: 'minLength', label: 'Мин. длина строки'},
  {value: 'maxLength', label: 'Макс. длина строки'},
  {value: 'regex', label: 'Regex'},
  {value: 'unique', label: 'Уникальность'},
  {value: 'custom', label: 'Кастомная'},
  {value: 'server', label: 'Серверная валидация'},
];

export const DIRECTORY_TYPE_OPTIONS: ReadonlyArray<{
  value: DirectoryType;
  label: string;
}> = [
  {value: 'list', label: 'Список объектов'},
  {value: 'single', label: 'Один объект'},
  {value: 'file', label: 'Файл (JSON/YAML)'},
];

export const FILE_DIRECTORY_FORMAT_OPTIONS: ReadonlyArray<{
  value: FileDirectoryFormat;
  label: string;
}> = [
  {value: 'json', label: 'JSON'},
  {value: 'yaml', label: 'YAML'},
];
