import {FieldDefinition, FieldType, FieldValidation} from '../models/directory.models';
import {SchemaBuilderService} from '../services/schema-builder.service';

export const MAX_OBJECT_NESTING_DEPTH = 5;

export const MAX_JSON_OBJECT_NESTING_DEPTH = 3;

export const OBJECT_NESTING_LIMIT_HINT =
  'Вложенность ограничена 5 уровнями, можете воспользоваться типом JSON';

export const JSON_OBJECT_NESTING_LIMIT_HINT =
  'Вложенность объектов в JSON ограничена 3 уровнями';

export function cloneField(field: FieldDefinition): FieldDefinition {
  return {
    ...field,
    fields: (field.fields ?? []).map((nested) => cloneField(nested)),
    enumValues: [...(field.enumValues || [])],
    validations: field.validations.map((v) => ({...v})),
  };
}

export function createEmptyField(id: string): FieldDefinition {
  return {
    id,
    name: '',
    description: '',
    type: 'string',
    isList: false,
    fields: [],
    enumValues: [],
    validations: [],
  };
}

export function validateField(
  field: FieldDefinition,
  otherNames: string[],
  schemaBuilder: SchemaBuilderService,
): string | null {
  const name = field.name.trim();
  if (!name) {
    return 'Укажите имя поля';
  }
  if (!schemaBuilder.isSystemIdField(field) && name === 'id') {
    return 'Имя «id» зарезервировано системным полем';
  }
  if (otherNames.includes(name)) {
    return 'Имена полей должны быть уникальны';
  }
  if (field.type === 'enum' && !field.enumValues?.length) {
    return `Поле «${name}»: задайте значения enum`;
  }
  if (field.type === 'reference' && !field.referenceDirectoryId) {
    return `Поле «${name}»: выберите справочник-ссылку`;
  }
  for (const v of field.validations) {
    if (v.kind === 'server' && !v.serverValidatorId) {
      return `Поле «${name}»: выберите серверный валидатор`;
    }
    if (v.kind === 'custom' && !v.customRule?.trim()) {
      return `Поле «${name}»: опишите кастомное правило`;
    }
    if (
      ['min', 'max', 'minLength', 'maxLength', 'regex'].includes(v.kind) &&
      (v.value === undefined || v.value === '')
    ) {
      return `Поле «${name}»: укажите значение для валидации ${v.kind}`;
    }
  }
  return null;
}

export function validateNestedFields(
  parent: FieldDefinition,
  schemaBuilder: SchemaBuilderService,
  path = parent.name.trim(),
): string | null {
  if (parent.type !== 'object') {
    return null;
  }
  const nested = parent.fields ?? [];
  const names = new Set<string>();
  for (const field of nested) {
    const fieldName = field.name.trim();
    if (!fieldName) {
      return `Объект «${path}»: укажите имя каждого вложенного поля`;
    }
    if (fieldName === 'id') {
      return `Объект «${path}»: имя «id» зарезервировано`;
    }
    if (names.has(fieldName)) {
      return `Объект «${path}»: имена вложенных полей должны быть уникальны`;
    }
    names.add(fieldName);
    const message = validateField(
      field,
      nested.filter((f) => f !== field).map((f) => f.name.trim()),
      schemaBuilder,
    );
    if (message) {
      return `Объект «${path}»: ${message}`;
    }
    const childError = validateNestedFields(field, schemaBuilder, `${path}.${fieldName}`);
    if (childError) {
      return childError;
    }
  }
  return null;
}

export function normalizeField(field: FieldDefinition): FieldDefinition {
  return {
    ...field,
    name: field.name.trim(),
    description: field.description.trim(),
    fields: field.type === 'object' ? field.fields ?? [] : [],
    enumValues: field.enumValues ?? [],
  };
}

export function patchField(
  field: FieldDefinition,
  patch: Partial<FieldDefinition>,
  schemaBuilder: SchemaBuilderService,
): FieldDefinition {
  if (schemaBuilder.isSystemIdField(field)) {
    return {...field, description: patch.description ?? field.description};
  }
  const next = {...field, ...patch};
  if (patch.type && !schemaBuilder.typeSupportsList(patch.type)) {
    next.isList = false;
  }
  if (patch.type && patch.type !== 'enum') {
    next.enumValues = [];
  }
  if (patch.type && patch.type !== 'reference') {
    next.referenceDirectoryId = undefined;
  }
  if (patch.type && patch.type !== 'object') {
    next.fields = [];
  }
  return next;
}

export function typeBadge(type: FieldType): string {
  const labels: Record<FieldType, string> = {
    string: 'Строка',
    bool: 'Булево',
    int: 'Число',
    object: 'Объект',
    json: 'JSON',
    enum: 'Перечисление',
    autoincrement: 'Автоинкремент',
    uuid: 'UUID',
    autogenerated_uuid: 'UUID',
    reference: 'Ссылка',
  };
  return labels[type] ?? type;
}

export function fieldTypeLabel(field: FieldDefinition): string {
  const type = typeBadge(field.type);
  return field.isList ? `${type} · Список` : type;
}

export function createValidation(id: string): FieldValidation {
  return {id, kind: 'required'};
}
